name: odm360

channels:
  - conda-forge

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.py
dependencies:
  - black
  - numpy
  - pip
  - pytest
  - pytest-cov
  - pytest-benchmark
  - python>=3.7
  - setuptools_scm
  - pip:
    - gphoto2
    - hydroengine

